version: "3"

services:
  web:
    container_name: braainy_web
    image: ifpb/php:7.4-apache-pdo
    build: .
    networks:
      - app-tier
    ports:
      - 8088:80
    volumes:
      - ./:/var/www/html/
    depends_on:
      - mysql

  mysql:
    container_name: braainy_mysql
    image: mysql:8.0
    command:
      - --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: braainy
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devuser
    networks:
      - app-tier
    ports:
      - 3307:3306

  adminer:
    container_name: braainy_adminer
    image: adminer:4.7.5
    restart: always
    networks:
      - app-tier
    ports:
      - 8081:8080
    depends_on:
      - mysql

networks:
  app-tier:
    driver: bridge